/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Jmail;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ClientTest {
    @Test void appHasAGreeting() {
        Client classUnderTest = new Client();
        assertNotNull(classUnderTest.getGreeting(), "Client should have a greeting");
    }
}
